server:
  port: 9006
xxl:
  job:
    admin:
#      addresses:
      addresses: http://192.168.8.121:8999/xxl-job-admin
    executor:
      appname: dentsumcgb
      ip: localhost
      port: 9007
      logpath: /applogs/
      logretentiondays: -1
    accessToken:

spring:
  application:
    name: dentsumcgb-data-executor
  profiles:
    active: local
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 18000
      connection-timeout: 6000
      max-lifetime: 900000
      connection-test-query: select 1
      validation-timeout: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.epoch.dentsumcgb.entity
logging:
  level:
    tk.mybatis: DEBUG
    com.epoch.dentsumcgb.mapper: DEBUG

---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/dentsu?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password:

smb:
  ip: 10.69.129.53
  userName: shushu.cui%40dentsu.com
  #  userName: shushu.cui@dentsu.com
  #  passWord: CVdDK#c!G!0uJKph
  passWord: CVdDK%23c!G!0uJKph
  #  sharePath: \\CNSR1FSM01\Aegis Groups
  sharePath: /Aegis Groups/DAN Finance/HQ Operational Finance/11. AIO_ACT_DATA/
  d365: 01. D365/
  hyp: 02. HYP/
  epayroll: 03. EPAYROLL/
  bpc: 04. BPC/
  backupPath: 05. BACKUP/
  local:
    path: D:/ideawork/test/
    d365: hypData/D365Data/
    hyp: hypData/
    epayroll: hypData/payrollData/
    bpc:

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.68.81.19:3306/c1_ods?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: c1_ods
    password: console&TY324

smb:
  ip: 10.69.129.53
  userName: shushu.cui%40dentsu.com
  #  userName: shushu.cui@dentsu.com
  #  passWord: CVdDK#c!G!0uJKph
  passWord: CVdDK%23c!G!0uJKph
  #  sharePath: \\CNSR1FSM01\Aegis Groups
  sharePath: /Aegis Groups/DAN Finance/HQ Operational Finance/11. AIO_ACT_DATA/
  d365: 01. D365/
  hyp: 02. HYP/
  epayroll: 03. EPAYROLL/
  bpc: 04. BPC/
  backupPath: 05. BACKUP/
  local:
    path: /yuanian/backupData/
    d365: hypData/D365Data/
    hyp: hypData/
    epayroll: hypData/payrollData/
    bpc: